// Code generated by MockGen. DO NOT EDIT.
// Source: s3.go
//
// Generated by this command:
//
//	mockgen -source=s3.go -destination=s3_mock.go -package storage IS3Client
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIS3Client is a mock of IS3Client interface.
type MockIS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockIS3ClientMockRecorder
	isgomock struct{}
}

// MockIS3ClientMockRecorder is the mock recorder for MockIS3Client.
type MockIS3ClientMockRecorder struct {
	mock *MockIS3Client
}

// NewMockIS3Client creates a new mock instance.
func NewMockIS3Client(ctrl *gomock.Controller) *MockIS3Client {
	mock := &MockIS3Client{ctrl: ctrl}
	mock.recorder = &MockIS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIS3Client) EXPECT() *MockIS3ClientMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockIS3Client) PresignGetObject(ctx context.Context, objectKey string, expires time.Duration) (*PresignedGetRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGetObject", ctx, objectKey, expires)
	ret0, _ := ret[0].(*PresignedGetRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockIS3ClientMockRecorder) PresignGetObject(ctx, objectKey, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockIS3Client)(nil).PresignGetObject), ctx, objectKey, expires)
}

// PresignPutObject mocks base method.
func (m *MockIS3Client) PresignPutObject(ctx context.Context, objectKey string, expires time.Duration) (*PresignedPutRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPutObject", ctx, objectKey, expires)
	ret0, _ := ret[0].(*PresignedPutRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockIS3ClientMockRecorder) PresignPutObject(ctx, objectKey, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockIS3Client)(nil).PresignPutObject), ctx, objectKey, expires)
}
